### ISSUE TITLE
Party initiative + combat tracker broken

### ISSUE THREAD

**Issue by mcglincy** [fvtt-fria-ligan/morkborg-foundry-vtt#132]
Error in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at MBCombat.isFriendlyCombatant (systems/morkborg/module/combat.js:84:29)
    at _sortCombatants (systems/morkborg/module/combat.js:96:36)
    at Array.sort (<anonymous>)
    at MBCombat.setupTurns (foundry.js:15739:44)
    at MBCombat._onUpdate (foundry.js:15797:35)
    at ClientDatabaseBackend.callback (foundry.js:10241:11)
    at foundry.js:10193:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10193:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:10074:17)
```

**Comment by mcglincy** [comment]
Fixed in 1.6.2.
